version: 2.1

parameters:
  FIRST:
    type: string
    default: 'NGUYEN MINH'
  LAST: 
    type: string
    default: 'VUONG'

commands:
  duplicate: 
    description: 'commands are duplicate'
    parameters:
      to:
        type: string
        default: "wellcome to parameter to"
    steps:
      - run: 
          name: 'run in commands'
          command: who
      - run: 
          name: 'show value of the parameter to'
          command: echo << parameters.to >>
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'run the first'
          command: ls
      - run:
          name: 'run the second'
          command: who
      - run:
          name: 'show author'
          command: echo "${pipeline.parameters.FIRST} ${pipeline.parameters.LAST}"
      # - add_ssh_keys:
      #     fingerprints:
      #       - "f0:54:20:62:c0:b2:38:e9:61:19:47:08:ec:16:61:cb"
      # - run:
      #     name: "check cmd"
      #     command: git rev-parse --abbrev-ref HEAD
      # - run:
      #     name: "remote server"
      #     command: ssh -t ec2-user@3.140.239.254 "cd circleci-node;git pull;pm2 restart app"
  learning:
    machine: true
    steps:
      - checkout
      - duplicate
      - run:
          name: 'run the learning'
          command: ls



# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-test:
    jobs:
      - deploy
      - learning:
          requires:
            - deploy
          # filters:
          #   branches:
          #     only: develop

          # type: approval
