version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'run the first'
          command: ls
      - run:
          name: 'run the second'
          command: who
      # - add_ssh_keys:
      #     fingerprints:
      #       - "f0:54:20:62:c0:b2:38:e9:61:19:47:08:ec:16:61:cb"
      # - run:
      #     name: "check cmd"
      #     command: git rev-parse --abbrev-ref HEAD
      # - run:
      #     name: "remote server"
      #     command: ssh -t ec2-user@3.140.239.254 "cd circleci-node;git pull;pm2 restart app"
  learning:
    machine: true
    steps:
      - checkout
      - run:
          name: 'run the learning'
          command: ls



# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-test:
    jobs:
      - deploy
      - learning:
          requires:
            - deploy
          # filters:
          #   branches:
          #     only: develop

          # type: approval
